/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "tertiary": "#904400",
        "on-tertiary-fixed": "#321300",
        "on-surface": "#191c1d",
        "on-secondary-container": "#474984",
        "on-error-container": "#93000a",
        "background": "#f8f9fa",
        "error-container": "#ffdad6",
        "on-primary-container": "#faf7ff",
        "on-secondary": "#ffffff",
        "secondary-fixed-dim": "#c1c1ff",
        "on-primary": "#ffffff",
        "outline": "#767586",
        "on-tertiary-fixed-variant": "#743500",
        "primary-fixed-dim": "#c1c1ff",
        "secondary-container": "#babbfe",
        "outline-variant": "#c7c4d7",
        "on-secondary-fixed-variant": "#3f417b",
        "surface": "#f8f9fa",
        "error": "#ba1a1a",
        "surface-dim": "#d9dadb",
        "inverse-primary": "#c1c1ff",
        "on-primary-fixed": "#07006c",
        "on-tertiary": "#ffffff",
        "on-secondary-fixed": "#12134d",
        "on-background": "#191c1d",
        "surface-bright": "#f8f9fa",
        "surface-container-highest": "#e1e3e4",
        "secondary-fixed": "#e1e0ff",
        "on-tertiary-container": "#fff6f3",
        "tertiary-fixed": "#ffdbc8",
        "on-error": "#ffffff",
        "surface-tint": "#4849da",
        "inverse-surface": "#2e3132",
        "surface-container": "#edeeef",
        "primary": "#4343d5",
        "secondary": "#575995",
        "primary-fixed": "#e1e0ff",
        "tertiary-container": "#b65700",
        "inverse-on-surface": "#f0f1f2",
        "surface-variant": "#e1e3e4",
        "on-surface-variant": "#464555",
        "on-primary-fixed-variant": "#2e2bc2",
        "tertiary-fixed-dim": "#ffb689",
        "primary-container": "#5d5fef",
        "surface-container-high": "#e7e8e9",
        "surface-container-lowest": "#ffffff",
        "surface-container-low": "#f3f4f5"
      },
      fontFamily: {
        "headline": ["Manrope", "sans-serif"],
        "body": ["Newsreader", "serif"],
        "label": ["Inter", "sans-serif"]
      },
      borderRadius: {"DEFAULT": "0.25rem", "lg": "0.5rem", "xl": "0.75rem", "full": "9999px"},
    },
  },
  plugins: [],
}
