/**
 * AuraSphere Agent Framework — Mock LLM Provider
 *
 * A deterministic LLM provider implementation for development and testing.
 * Generates responses by hashing the first message content, ensuring
 * identical inputs always produce identical outputs.
 *
 * Supports configurable latency to simulate real-world network conditions.
 *
 * @module agent/providers/MockProvider
 * Requirements: 1.7, 1.8, 1.9, 1.15
 */

import type { CompletionParams, CompletionResult, ModelCapabilities } from '../types';
import { AgentError } from '../errors/AgentError';
import type { LLMProvider } from './LLMProvider';

// ---------------------------------------------------------------------------
// Configuration
// ---------------------------------------------------------------------------

export interface MockProviderConfig {
  /** Simulated response latency in milliseconds (0-30000, default 0). */
  latencyMs?: number;
}

// ---------------------------------------------------------------------------
// MockProvider Implementation
// ---------------------------------------------------------------------------

/**
 * Mock LLM Provider that returns deterministic responses derived from input.
 *
 * The response is generated by hashing the content of the first message in
 * the messages array, producing a fixed string that is always the same for
 * the same input. This enables reliable testing without external dependencies.
 */
export class MockProvider implements LLMProvider {
  readonly providerId = 'mock';
  private readonly latencyMs: number;

  constructor(config?: MockProviderConfig) {
    const latency = config?.latencyMs ?? 0;

    if (latency < 0 || latency > 30000) {
      throw new AgentError(
        'INVALID_REQUEST',
        `MockProvider latencyMs must be between 0 and 30000, got ${latency}`,
      );
    }

    this.latencyMs = latency;
  }

  /**
   * Generate a deterministic completion from the first message content.
   *
   * Validates input parameters and returns INVALID_REQUEST for out-of-bounds values.
   * The response content is derived by hashing the first message.
   */
  async generateCompletion(params: CompletionParams): Promise<CompletionResult> {
    this.validateParams(params);

    if (this.latencyMs > 0) {
      await this.delay(this.latencyMs);
    }

    const responseContent = this.generateDeterministicResponse(params.messages[0].content);
    const tokensUsed = Math.ceil(responseContent.length / 4);

    return {
      content: responseContent,
      tokens_used: tokensUsed,
      finish_reason: 'stop',
    };
  }

  /**
   * Generate a streaming completion yielding word-sized token chunks.
   *
   * Splits the deterministic response into words and yields each with
   * the configured latency between chunks.
   */
  async *generateStream(params: CompletionParams): AsyncIterable<string> {
    this.validateParams(params);

    const responseContent = this.generateDeterministicResponse(params.messages[0].content);
    const chunks = this.splitIntoChunks(responseContent);

    for (const chunk of chunks) {
      if (this.latencyMs > 0) {
        await this.delay(this.latencyMs);
      }
      yield chunk;
    }
  }

  /**
   * Report model capabilities for the mock provider.
   */
  getModelCapabilities(): ModelCapabilities {
    return {
      max_context_length: 128000,
      supports_function_calling: true,
      supports_streaming: true,
      supported_output_formats: ['text', 'json', 'markdown'],
    };
  }

  // ---------------------------------------------------------------------------
  // Private Helpers
  // ---------------------------------------------------------------------------

  /**
   * Validate completion parameters against allowed bounds.
   * Throws AgentError with INVALID_REQUEST for invalid values.
   */
  private validateParams(params: CompletionParams): void {
    if (!params.messages || params.messages.length === 0) {
      throw new AgentError(
        'INVALID_REQUEST',
        'messages must contain at least 1 message',
        undefined,
        undefined,
        false,
      );
    }

    if (params.temperature < 0.0 || params.temperature > 2.0) {
      throw new AgentError(
        'INVALID_REQUEST',
        `temperature must be between 0.0 and 2.0, got ${params.temperature}`,
        undefined,
        undefined,
        false,
      );
    }

    if (
      params.max_tokens < 1 ||
      params.max_tokens > 128000 ||
      !Number.isInteger(params.max_tokens)
    ) {
      throw new AgentError(
        'INVALID_REQUEST',
        `max_tokens must be an integer between 1 and 128000, got ${params.max_tokens}`,
        undefined,
        undefined,
        false,
      );
    }

    if (params.stop_sequences && params.stop_sequences.length > 4) {
      throw new AgentError(
        'INVALID_REQUEST',
        `stop_sequences must contain at most 4 sequences, got ${params.stop_sequences.length}`,
        undefined,
        undefined,
        false,
      );
    }
  }

  /**
   * Generate a deterministic response string by hashing the input content.
   *
   * Uses a simple djb2-style hash to produce a numeric seed, then generates
   * a fixed pseudo-random sentence from a vocabulary set.
   */
  private generateDeterministicResponse(content: string): string {
    const hash = this.hashString(content);
    const words = [
      'the', 'quick', 'brown', 'fox', 'jumps', 'over', 'lazy', 'dog',
      'alpha', 'beta', 'gamma', 'delta', 'epsilon', 'zeta', 'eta', 'theta',
      'lorem', 'ipsum', 'dolor', 'sit', 'amet', 'consectetur', 'adipiscing', 'elit',
      'mock', 'response', 'generated', 'from', 'input', 'hash', 'value', 'output',
    ];

    const wordCount = 8 + (Math.abs(hash) % 17); // 8-24 words
    const result: string[] = [];

    let seed = Math.abs(hash);
    for (let i = 0; i < wordCount; i++) {
      seed = (seed * 1103515245 + 12345) & 0x7fffffff;
      result.push(words[seed % words.length]);
    }

    return result.join(' ');
  }

  /**
   * Simple djb2 hash function for strings.
   * Produces a deterministic 32-bit integer from any string input.
   */
  private hashString(str: string): number {
    let hash = 5381;
    for (let i = 0; i < str.length; i++) {
      hash = ((hash << 5) + hash + str.charCodeAt(i)) | 0;
    }
    return hash;
  }

  /**
   * Split a response string into word-sized chunks (preserving spaces).
   * Each chunk is a word followed by a space (except the last).
   */
  private splitIntoChunks(text: string): string[] {
    const words = text.split(' ');
    return words.map((word, index) => (index < words.length - 1 ? word + ' ' : word));
  }

  /**
   * Async delay helper.
   */
  private delay(ms: number): Promise<void> {
    return new Promise((resolve) => setTimeout(resolve, ms));
  }
}
